# Generated by Django 4.1.1 on 2022-10-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_rename_author_blog_user_remove_category_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='User',
            new_name='author',
        ),
    ]
